# Generated by Django 5.0.6 on 2024-07-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='vehicle_img')),
                ('category', models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car')], max_length=100)),
            ],
        ),
    ]
