# Generated by Django 5.0.6 on 2024-07-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike')], max_length=100),
        ),
    ]
